<div class="grid-2">
<div><label>Campus</label><select name="campus_id">@foreach($campuses as $campus)<option value="{{ $campus->id }}" @selected(old('campus_id',$group->campus_id ?? '')==$campus->id)>{{ $campus->name }}</option>@endforeach</select></div>
<div><label>Curso</label><select name="course_id">@foreach($courses as $course)<option value="{{ $course->id }}" @selected(old('course_id',$group->course_id ?? '')==$course->id)>{{ $course->name }}</option>@endforeach</select></div>
<div><label>Profesor</label><select name="teacher_id"><option value="">Sin asignar</option>@foreach($teachers as $teacher)<option value="{{ $teacher->id }}" @selected(old('teacher_id',$group->teacher_id ?? '')==$teacher->id)>{{ $teacher->full_name }}</option>@endforeach</select></div>
<div><label>Nombre</label><input name="name" value="{{ old('name',$group->name ?? '') }}"></div>
<div><label>Periodo</label><select name="period"><option value="">Seleccione</option>@foreach($periodOptions as $period)<option value="{{ $period }}" @selected(old('period',$group->period ?? '')==$period)>{{ $period }}</option>@endforeach @if(!empty($group->period ?? null) && !in_array($group->period, $periodOptions, true))<option value="{{ $group->period }}" selected>{{ $group->period }} (actual)</option>@endif</select></div>
<div><label>Horario</label><select name="schedule"><option value="">Seleccione</option>@foreach($scheduleOptions as $schedule)<option value="{{ $schedule }}" @selected(old('schedule',$group->schedule ?? '')==$schedule)>{{ $schedule }}</option>@endforeach @if(!empty($group->schedule ?? null) && !in_array($group->schedule, $scheduleOptions, true))<option value="{{ $group->schedule }}" selected>{{ $group->schedule }} (actual)</option>@endif</select></div>
<div><label>Inicio</label><input type="date" name="start_date" value="{{ old('start_date',isset($group->start_date)?$group->start_date?->format('Y-m-d'):'') }}"></div>
<div><label>Fin</label><input type="date" name="end_date" value="{{ old('end_date',isset($group->end_date)?$group->end_date?->format('Y-m-d'):'') }}"></div>
<div><label>Status</label><select name="status">@foreach($statusOptions as $status)<option value="{{ $status }}" @selected(old('status',$group->status ?? 'active')==$status)>{{ $status }}</option>@endforeach @if(!empty($group->status ?? null) && !in_array($group->status, $statusOptions, true))<option value="{{ $group->status }}" selected>{{ $group->status }} (actual)</option>@endif</select></div>
<div><label>Capacidad</label><input type="number" min="1" max="200" name="capacity" value="{{ old('capacity',$group->capacity ?? '') }}" placeholder="Ej. 20"></div>
</div>
